<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Microsoft SQL Server provider for EzDbSchema, enabling schema analysis and code generation for SQL Server databases.</Description>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>EzDbSchema.MsSql</PackageId>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <OutputPath>bin\$(Configuration)</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EzDbSchema.Core\EzDbSchema.Core.csproj" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>True</Optimize>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Optimize>True</Optimize>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
</Project>
